DROP TABLE IF EXISTS teacher;
CREATE TABLE teacher (
id INT AUTO_INCREMENT  PRIMARY KEY,
name VARCHAR(100) NOT NULL,
lastname VARCHAR(100) NOT NULL,
document VARCHAR(100) NOT NULL,
age VARCHAR(10) NOT NULL,
course VARCHAR(50) NOT NULL
);

DROP TABLE IF EXISTS student;
CREATE TABLE student (
id INT AUTO_INCREMENT  PRIMARY KEY,
name VARCHAR(100) NOT NULL,
lastname VARCHAR(100) NOT NULL,
birthdate VARCHAR(100) NOT NULL,
document VARCHAR(100) NOT NULL,
age VARCHAR(10) NOT NULL,
course VARCHAR(50) NOT NULL
);

DROP TABLE IF EXISTS course;
CREATE TABLE course (
id INT AUTO_INCREMENT  PRIMARY KEY,
student VARCHAR(100) NOT NULL,
teacher VARCHAR(100) NOT NULL,
schedule VARCHAR(100) NOT NULL,
topic VARCHAR(10) NOT NULL);